class CreateWarlords < ActiveRecord::Migration[6.1]
  def change
    create_table :warlords do |t|
      t.integer :ttrn_borders
      t.integer :ttrn_police
      t.integer :ttrn_guards
      t.integer :ttrn_leaders
      t.integer :revives
      t.integer :markettime
      t.integer :newstime
      t.integer :msgtime
      t.integer :aidcred
      t.integer :bmperskiff
      t.integer :bmperstoat
      t.integer :bmperweasel
      t.integer :bmperrat
      t.integer :pmkt_food
      t.integer :pmkt_skiff
      t.integer :pmkt_stoat
      t.integer :pmkt_weasel
      t.integer :pmkt_rat
      t.integer :loan
      t.integer :savings
      t.integer :tax
      t.integer :freeland
      t.integer :towers
      t.integer :farms
      t.integer :huts
      t.integer :camps
      t.integer :barracks
      t.integer :tents
      t.integer :markets
      t.integer :land
      t.integer :ind_skiff
      t.integer :ind_stoat
      t.integer :ind_weasel
      t.integer :ind_rat
      t.integer :gate
      t.integer :shield
      t.integer :loyalty
      t.integer :leaders
      t.integer :health
      t.integer :skiffs 
      t.integer :stoats
      t.integer :weasels
      t.integer :rats
      t.integer :workers
      t.integer :food
      t.integer :cash
      t.integer :networth
      t.integer :turnsused
      t.integer :turnsstored
      t.integer :turns
      t.integer :kills
      t.integer :deftotal
      t.integer :defsucc
      t.integer :offtotal
      t.integer :offsucc
      t.integer :attacks
      t.boolean :forces
      t.integer :clantime
      t.integer :allytime
      t.integer :clan_status
      t.integer :clan_request
      t.integer :clan_id
      t.integer :rank
      t.string :notice
      t.integer :location_id
      t.integer :race_id
      t.string :name
      t.integer :user_id
      t.integer :army_id
      t.string :coa_url
      t.boolean :validated
      t.boolean :online
      t.boolean :vacation
      t.string :style
      t.boolean :atkcondense
      t.integer :race_change
      t.boolean :free_revolt
      t.integer :show_taxloot
      t.timestamps
    end
  end
end
