class CreateWarlords < ActiveRecord::Migration[6.1]
  def change
    create_table :warlords do |t|
      t.integer :ttrn_borders
      t.integer :ttrn_police
      t.integer :ttrn_guards
      t.integer :ttrn_leaders
      t.integer :revives
      t.integer :markettime
      t.integer :newstime
      t.integer :msgtime
      t.integer :aidcred
      t.integer :bmperwatertrp
      t.integer :bmperflytrp
      t.integer :bmperlndtrp
      t.integer :bmperarmtrp
      t.integer :pmkt_food
      t.integer :pmkt_watertrp
      t.integer :pmkt_flytrp
      t.integer :pmkt_lndtrp
      t.integer :pmkt_armtrp
      t.integer :loan
      t.integer :savings
      t.integer :tax
      t.integer :freeland
      t.integer :towers
      t.integer :farms
      t.integer :labs
      t.integer :barracks
      t.integer :industry
      t.integer :homes
      t.integer :shop
      t.integer :land
      t.integer :ind_watertrp
      t.integer :ind_flytrp
      t.integer :ind_lndtrp
      t.integer :ind_armtrp
      t.integer :gate
      t.integer :shield
      t.integer :runes
      t.integer :wizards
      t.integer :health
      t.integer :watertrp 
      t.integer :flytrp
      t.integer :ldntrp
      t.integer :armtrp
      t.integer :peasants
      t.integer :food
      t.integer :cash
      t.integer :networth
      t.integer :turnsused
      t.integer :turnsstored
      t.integer :turns
      t.integer :kills
      t.integer :deftotal
      t.integer :defsucc
      t.integer :offtotal
      t.integer :offsucc
      t.integer :attacks
      t.boolean :forces
      t.integer :clantime
      t.integer :allytime
      t.integer :clan_status
      t.integer :clan_request
      t.integer :clan_id
      t.integer :rank
      t.string :notice
      t.integer :location_id
      t.integer :race_id
      t.string :warlord_name
      t.boolean :validated
      t.boolean :online
      t.boolean :vacation
      t.string :style
      t.boolean :atkcondense
      t.integer :race_change
      t.boolean :free_revolt
      t.integer :show_taxloot
      t.timestamps
    end
  end
end
